// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_Multiplex_Header_and_Data_Signals.v
// Created: 2023-05-02 12:36:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_Multiplex_Header_and_Data_Signals
// Source Path: whdlOFDMTx/Multiplexer/Multiplex Header and Data Signals
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_Multiplex_Header_and_Data_Signals
          (header_re,
           header_im,
           headerValid,
           data_re,
           data_im,
           dataValid,
           dataOut_re,
           dataOut_im,
           validOut);


  input   signed [15:0] header_re;  // sfix16_En14
  input   signed [15:0] header_im;  // sfix16_En14
  input   headerValid;
  input   signed [15:0] data_re;  // sfix16_En14
  input   signed [15:0] data_im;  // sfix16_En14
  input   dataValid;
  output  signed [15:0] dataOut_re;  // sfix16_En14
  output  signed [15:0] dataOut_im;  // sfix16_En14
  output  validOut;


  wire signed [15:0] Switch_out1_re;  // sfix16_En14
  wire signed [15:0] Switch_out1_im;  // sfix16_En14
  wire Logical_Operator_out1;


  assign Switch_out1_re = (headerValid == 1'b0 ? data_re :
              header_re);
  assign Switch_out1_im = (headerValid == 1'b0 ? data_im :
              header_im);



  assign dataOut_re = Switch_out1_re;

  assign dataOut_im = Switch_out1_im;

  assign Logical_Operator_out1 = headerValid | dataValid;



  assign validOut = Logical_Operator_out1;

endmodule  // whdlOFDMTx_Multiplex_Header_and_Data_Signals

