// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_Pulse_Generator.v
// Created: 2023-05-02 12:36:36
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_Pulse_Generator
// Source Path: whdlOFDMTx/Frame Controller and Input Sampler/Frame Controller/Generate OFDM Modulator Ready/Control 
// OFDM Signal Generation/Pulse Generato
// Hierarchy Level: 6
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_Pulse_Generator
          (clk,
           reset,
           enb_1_2_0,
           pulse);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  output  pulse;


  wire Constant_out1;
  wire Logical_Operator4_out1;
  reg  Delay3_out1;
  wire Logical_Operator3_out1;


  assign Constant_out1 = 1'b1;



  assign Logical_Operator4_out1 =  ~ Constant_out1;



  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b1;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1 <= Logical_Operator4_out1;
        end
      end
    end



  assign Logical_Operator3_out1 = Constant_out1 & Delay3_out1;



  assign pulse = Logical_Operator3_out1;

endmodule  // whdlOFDMTx_Pulse_Generator

