// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_Control_OFDM_Signal_Generation.v
// Created: 2023-05-02 12:36:36
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_Control_OFDM_Signal_Generation
// Source Path: whdlOFDMTx/Frame Controller and Input Sampler/Frame Controller/Generate OFDM Modulator Ready/Control 
// OFDM Signal Generatio
// Hierarchy Level: 5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_Control_OFDM_Signal_Generation
          (clk,
           reset,
           enb_1_2_0,
           readyLow,
           reset_1,
           holdOFDMGen);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   readyLow;
  input   reset_1;
  output  holdOFDMGen;


  wire Pulse_Generator_out1;
  wire Logical_Operator6_out1;
  wire out;
  wire Falling_Edge_Detector_out1;
  wire out_1;
  wire Logical_Operator11_out1;
  wire Logical_Operator8_out1;


  whdlOFDMTx_Pulse_Generator u_Pulse_Generator (.clk(clk),
                                                .reset(reset),
                                                .enb_1_2_0(enb_1_2_0),
                                                .pulse(Pulse_Generator_out1)
                                                );

  assign Logical_Operator6_out1 = Pulse_Generator_out1 | reset_1;



  whdlOFDMTx_MATLAB_Function2 u_MATLAB_Function2 (.clk(clk),
                                                  .reset(reset),
                                                  .enb_1_2_0(enb_1_2_0),
                                                  .trigger(Logical_Operator6_out1),
                                                  .out(out)
                                                  );

  whdlOFDMTx_Falling_Edge_Detector u_Falling_Edge_Detector (.clk(clk),
                                                            .reset(reset),
                                                            .enb_1_2_0(enb_1_2_0),
                                                            .in(out),
                                                            .out(Falling_Edge_Detector_out1)
                                                            );

  whdlOFDMTx_Disable_OFDM_Generation u_Disable_OFDM_Generation (.clk(clk),
                                                                .reset(reset),
                                                                .enb_1_2_0(enb_1_2_0),
                                                                .readyLow(readyLow),
                                                                .waitSignal(Falling_Edge_Detector_out1),
                                                                .out(out_1)
                                                                );

  assign Logical_Operator11_out1 = out | (out_1 | Falling_Edge_Detector_out1);



  assign Logical_Operator8_out1 =  ~ Logical_Operator11_out1;



  assign holdOFDMGen = Logical_Operator8_out1;

endmodule  // whdlOFDMTx_Control_OFDM_Signal_Generation

