// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_Generate_Ready.v
// Created: 2023-05-02 12:36:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_Generate_Ready
// Source Path: whdlOFDMTx/Frame Generator/Data/Data Chain/Symbol Interleaver/Interleaver/Generate Ready
// Hierarchy Level: 7
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_Generate_Ready
          (clk,
           reset,
           enb,
           advPop,
           fifoCount,
           pop,
           endReady,
           ready);


  input   clk;
  input   reset;
  input   enb;
  input   advPop;
  input   [2:0] fifoCount;  // ufix3
  input   pop;
  input   endReady;
  output  ready;


  wire Logical_Operator1_out1;
  wire Generate_Ready2_out1;
  wire out;
  wire Logical_Operator3_out1;
  wire Logical_Operator2_out1;


  assign Logical_Operator1_out1 = advPop & endReady;



  whdlOFDMTx_Generate_Ready2 u_Generate_Ready2 (.fifoCount(fifoCount),  // ufix3
                                                .pop(pop),
                                                .ready2(Generate_Ready2_out1)
                                                );

  whdlOFDMTx_MATLAB_Function1_block u_MATLAB_Function1 (.clk(clk),
                                                        .reset(reset),
                                                        .enb(enb),
                                                        .trigger(Logical_Operator1_out1),
                                                        .out(out)
                                                        );

  assign Logical_Operator3_out1 =  ~ out;



  assign Logical_Operator2_out1 = Generate_Ready2_out1 & Logical_Operator3_out1;



  assign ready = Logical_Operator2_out1;

endmodule  // whdlOFDMTx_Generate_Ready

