// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_Falling_Edge_Detector2.v
// Created: 2023-05-02 12:36:36
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_Falling_Edge_Detector2
// Source Path: whdlOFDMTx/Frame Controller and Input Sampler/Enable Header and Preamble /Falling Edge Detector2
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_Falling_Edge_Detector2
          (clk,
           reset,
           enb_1_2_0,
           in,
           out);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   in;
  output  out;


  reg  Delay3_out1;
  wire Logical_Operator2_out1;
  wire Logical_Operator1_out1;


  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1 <= in;
        end
      end
    end



  assign Logical_Operator2_out1 =  ~ in;



  assign Logical_Operator1_out1 = Delay3_out1 & Logical_Operator2_out1;



  assign out = Logical_Operator1_out1;

endmodule  // whdlOFDMTx_Falling_Edge_Detector2

