// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_Generate_Forced_End_block.v
// Created: 2023-05-02 12:36:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_Generate_Forced_End_block
// Source Path: whdlOFDMTx/Frame Generator/Header/Interleaver/Write Logic/Handle Input Control Signals/Generate Forced 
// En
// Hierarchy Level: 7
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_Generate_Forced_End_block
          (clk,
           reset,
           enb,
           rst,
           valid,
           frameOn,
           forcedEnd);


  input   clk;
  input   reset;
  input   enb;
  input   rst;
  input   valid;
  input   frameOn;
  output  forcedEnd;


  wire Logical_Operator1_out1;
  wire [6:0] count_step;  // ufix7
  wire [6:0] count_from;  // ufix7
  wire [6:0] count_reset;  // ufix7
  reg [6:0] currentAddr;  // ufix7
  wire [6:0] count;  // ufix7
  wire need_to_wrap;
  wire [6:0] count_value;  // ufix7
  wire [6:0] count_1;  // ufix7
  wire [6:0] count_2;  // ufix7
  wire Compare_To_Constant1_out1;
  wire Logical_Operator6_out1;


  assign Logical_Operator1_out1 = valid & frameOn;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 72
  assign count_step = 7'b0000001;



  assign count_from = 7'b0000000;



  assign count_reset = 7'b0000000;



  assign count = currentAddr + count_step;



  assign need_to_wrap = currentAddr == 7'b1001000;



  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);



  assign count_1 = (Logical_Operator1_out1 == 1'b0 ? currentAddr :
              count_value);



  assign count_2 = (rst == 1'b0 ? count_1 :
              count_reset);



  always @(posedge clk or posedge reset)
    begin : readyCounter_process
      if (reset == 1'b1) begin
        currentAddr <= 7'b0000000;
      end
      else begin
        if (enb) begin
          currentAddr <= count_2;
        end
      end
    end



  assign Compare_To_Constant1_out1 = currentAddr == 7'b1000110;



  assign Logical_Operator6_out1 = Compare_To_Constant1_out1 & Logical_Operator1_out1;



  assign forcedEnd = Logical_Operator6_out1;

endmodule  // whdlOFDMTx_Generate_Forced_End_block

