// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_Disable_OFDM_Generation.v
// Created: 2023-05-02 12:36:36
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_Disable_OFDM_Generation
// Source Path: whdlOFDMTx/Frame Controller and Input Sampler/Frame Controller/Generate OFDM Modulator Ready/Control 
// OFDM Signal Generation/Disable OFDM Generatio
// Hierarchy Level: 6
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_Disable_OFDM_Generation
          (clk,
           reset,
           enb_1_2_0,
           readyLow,
           waitSignal,
           out);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   readyLow;
  input   waitSignal;
  output  out;


  wire Logical_Operator13_out1;
  wire Logical_Operator12_out1;
  reg  Delay3_out1;


  assign Logical_Operator13_out1 =  ~ readyLow;



  assign Logical_Operator12_out1 = Logical_Operator13_out1 & waitSignal;



  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1 <= Logical_Operator12_out1;
        end
      end
    end



  whdlOFDMTx_MATLAB_Function5 u_MATLAB_Function5 (.clk(clk),
                                                  .reset(reset),
                                                  .enb_1_2_0(enb_1_2_0),
                                                  .trigger(Delay3_out1),
                                                  .out(out)
                                                  );

endmodule  // whdlOFDMTx_Disable_OFDM_Generation

