// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_OFDM_Modulator.v
// Created: 2023-05-02 12:36:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_OFDM_Modulator
// Source Path: whdlOFDMTx/Frame Formation and OFDM Modulation/OFDM Modulator
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_OFDM_Modulator
          (clk,
           reset,
           enb_1_32_0,
           data_re,
           data_im,
           valid,
           data1_re,
           data1_im,
           valid1,
           ready);


  input   clk;
  input   reset;
  input   enb_1_32_0;
  input   signed [15:0] data_re;  // sfix16_En14
  input   signed [15:0] data_im;  // sfix16_En14
  input   valid;
  output  signed [15:0] data1_re;  // sfix16_En14
  output  signed [15:0] data1_im;  // sfix16_En14
  output  valid1;
  output  ready;


  wire out;
  wire out_1;
  wire obj_readyLowFlag;
  wire out_2;
  wire out_3;
  wire [12:0] obj_readyLowCount;  // ufix13
  wire [12:0] obj_FFTLengthReg;  // ufix13
  wire [12:0] obj_CPLengthReg;  // ufix13
  wire [12:0] tmp;  // ufix13
  wire [12:0] obj_numLgScReg;  // ufix13
  wire [12:0] obj_insertDC;  // ufix13
  wire [12:0] obj_numRgScReg;  // ufix13
  wire [12:0] tmp_1;  // ufix13
  wire [12:0] tmp_2;  // ufix13
  wire [12:0] tmp_3;  // ufix13
  wire [12:0] tmp_4;  // ufix13
  wire obj_readyLowFlag_1;
  wire out_4;
  wire out_5;
  wire obj_validInHighFlag;
  wire out_6;
  wire out_7;
  wire [12:0] obj_validInHighCount;  // ufix13
  wire obj_validInHighFlag_1;
  wire out_8;
  wire out_9;
  wire obj_readyOut;
  wire obj_readyOut_1;
  wire obj_readyOut_2;
  wire obj_readyOut_3;
  wire out_10;
  wire out_11;
  wire tmp_5;
  wire tmp_6;
  wire tmp_7;
  wire tmp_8;
  reg [12:0] obj_validInHighCount_1;  // ufix13
  wire [12:0] tmp_9;  // ufix13
  wire [12:0] tmp_10;  // ufix13
  wire [12:0] tmp_11;  // ufix13
  wire [12:0] tmp_12;  // ufix13
  wire tmp_13;
  wire [12:0] tmp_14;  // ufix13
  wire tmp_15;
  wire tmp_16;
  reg [12:0] obj_readyLowCount_1;  // ufix13
  wire [12:0] tmp_17;  // ufix13
  wire [12:0] tmp_18;  // ufix13
  wire [12:0] tmp_19;  // ufix13
  wire [12:0] tmp_20;  // ufix13
  wire [12:0] tmp_21;  // ufix13
  wire tmp_22;
  wire tmp_23;
  wire tmp_24;
  wire tmp_25;
  wire tmp_26;
  reg  obj_readyLowFlag_2;
  reg  obj_validInHighFlag_2;
  wire tmp_27;
  wire tmp_28;
  wire tmp_29;
  wire tmp_30;
  wire tmp_31;
  wire tmp_32;
  wire tmp_33;
  wire tmp_34;
  wire tmp_35;
  wire tmp_36;
  wire tmp_37;
  wire tmp_38;
  reg  obj_delayedReady;
  wire tmp_39;
  wire signed [15:0] varargout_1_re;  // sfix16_En14
  wire signed [15:0] varargout_1_im;  // sfix16_En14
  wire varargout_2;
  wire signed [15:0] varargout_1_re_1;  // sfix16_En14
  wire signed [15:0] varargout_1_im_1;  // sfix16_En14
  wire varargout_2_1;
  wire signed [15:0] varargout_1_re_2;  // sfix16_En14
  wire signed [15:0] varargout_1_im_2;  // sfix16_En14
  wire varargout_2_2;
  wire signed [15:0] varargout_1_re_3;  // sfix16_En14
  wire signed [15:0] varargout_1_im_3;  // sfix16_En14
  wire varargout_2_3;
  reg signed [15:0] data_re_1;  // sfix16_En14
  reg signed [15:0] data_im_1;  // sfix16_En14
  reg  valid_1;
  wire tmp_40;
  wire [12:0] tmp_41;  // ufix13
  wire [12:0] obj_readyLast;  // ufix13
  wire [12:0] tmp_42;  // ufix13
  wire tmp_43;
  wire obj_readyFlag;
  wire tmp_44;
  wire obj_readyFlag_1;
  wire obj_readyFlag_2;
  wire tmp_45;
  reg  obj_readyFlag_3;
  wire tmp_46;
  wire tmp_47;
  wire tmp_48;
  wire tmp_49;
  wire tmp_50;
  wire [13:0] p115tmp_1;  // ufix14
  wire [13:0] p115tmp_2;  // ufix14
  wire tmp_51;
  wire obj_triggerReady;
  wire obj_triggerReady_1;
  reg  obj_triggerReady_2;
  wire tmp_52;
  wire tmp_53;
  wire tmp_54;
  reg  obj_readyOut_4;
  wire varargout_3;
  wire tmp_55;
  wire varargout_3_1;


  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp95
  assign out = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp95
  assign out_1 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp87
  assign obj_readyLowFlag = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp130
  assign out_2 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp130
  assign out_3 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp81
  assign obj_readyLowCount = 13'b0000000000000;



  assign obj_FFTLengthReg = 13'b0000010000000;



  assign obj_CPLengthReg = 13'b0000000100000;



  assign tmp = obj_FFTLengthReg + obj_CPLengthReg;



  assign obj_numLgScReg = 13'b0000000011100;



  assign obj_insertDC = 13'b0000000000001;



  assign obj_numRgScReg = 13'b0000000011011;



  assign tmp_1 = obj_numLgScReg + obj_numRgScReg;



  assign tmp_2 = obj_insertDC + tmp_1;



  assign tmp_3 = obj_FFTLengthReg - tmp_2;



  assign tmp_4 = tmp - tmp_3;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp109
  assign obj_readyLowFlag_1 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp100
  assign out_4 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp100
  assign out_5 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp84
  assign obj_validInHighFlag = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp135
  assign out_6 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp135
  assign out_7 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp78
  assign obj_validInHighCount = 13'b0000000000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp120
  assign obj_validInHighFlag_1 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp105
  assign out_8 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp105
  assign out_9 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp90
  assign obj_readyOut = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp90
  assign obj_readyOut_1 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp74
  assign obj_readyOut_2 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp58
  assign obj_readyOut_3 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp165
  assign out_10 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp165
  assign out_11 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp74
  assign tmp_6 = (tmp_5 == 1'b0 ? obj_readyOut :
              obj_readyOut_1);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp58
  assign tmp_8 = (tmp_7 == 1'b0 ? tmp_6 :
              obj_readyOut_2);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp126
  assign tmp_9 = obj_validInHighCount_1 + 13'b0000000000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp62
  assign tmp_11 = (tmp_5 == 1'b0 ? tmp_10 :
              obj_validInHighCount);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp42
  assign tmp_12 = (tmp_7 == 1'b0 ? tmp_11 :
              tmp_10);



  assign tmp_14 = (tmp_13 == 1'b0 ? tmp_12 :
              tmp_10);



  always @(posedge clk or posedge reset)
    begin : obj_validInHighCount_reg_process
      if (reset == 1'b1) begin
        obj_validInHighCount_1 <= 13'b0000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_validInHighCount_1 <= tmp_14;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp68
  assign tmp_16 = (tmp_5 == 1'b0 ? tmp_15 :
              obj_validInHighFlag);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp123
  assign tmp_17 = obj_readyLowCount_1 + 13'b0000000000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp65
  assign tmp_19 = (tmp_5 == 1'b0 ? tmp_18 :
              obj_readyLowCount);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp46
  assign tmp_20 = (tmp_7 == 1'b0 ? tmp_19 :
              tmp_18);



  assign tmp_21 = (tmp_13 == 1'b0 ? tmp_20 :
              tmp_18);



  always @(posedge clk or posedge reset)
    begin : obj_readyLowCount_reg_process
      if (reset == 1'b1) begin
        obj_readyLowCount_1 <= 13'b0000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_readyLowCount_1 <= tmp_21;
        end
      end
    end



  assign tmp_23 = tmp_15 && tmp_22;



  assign tmp_5 = (tmp_23 == 1'b0 ? out :
              out_1);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp71
  assign tmp_24 = (tmp_5 == 1'b0 ? tmp_22 :
              obj_readyLowFlag);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp54
  assign tmp_25 = (tmp_7 == 1'b0 ? tmp_24 :
              tmp_22);



  assign tmp_26 = (tmp_13 == 1'b0 ? tmp_25 :
              tmp_22);



  always @(posedge clk or posedge reset)
    begin : obj_readyLowFlag_reg_process
      if (reset == 1'b1) begin
        obj_readyLowFlag_2 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_readyLowFlag_2 <= tmp_26;
        end
      end
    end



  assign tmp_27 = obj_validInHighFlag_2 && ( ! obj_readyLowFlag_2);



  assign tmp_28 = (tmp_27 == 1'b0 ? out_2 :
              out_3);



  assign tmp_18 = (tmp_28 == 1'b0 ? obj_readyLowCount_1 :
              tmp_17);



  assign tmp_29 = tmp_18 == tmp_4;



  assign tmp_22 = (tmp_29 == 1'b0 ? obj_readyLowFlag_2 :
              obj_readyLowFlag_1);



  assign tmp_30 = tmp_15 && ( ! tmp_22);



  assign tmp_7 = (tmp_30 == 1'b0 ? out_4 :
              out_5);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp50
  assign tmp_31 = (tmp_7 == 1'b0 ? tmp_16 :
              tmp_15);



  assign tmp_32 = (tmp_13 == 1'b0 ? tmp_31 :
              tmp_15);



  always @(posedge clk or posedge reset)
    begin : obj_validInHighFlag_reg_process
      if (reset == 1'b1) begin
        obj_validInHighFlag_2 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_validInHighFlag_2 <= tmp_32;
        end
      end
    end



  assign tmp_34 = tmp_33 && ( ! obj_validInHighFlag_2);



  assign tmp_35 = (tmp_34 == 1'b0 ? out_6 :
              out_7);



  assign tmp_10 = (tmp_35 == 1'b0 ? obj_validInHighCount_1 :
              tmp_9);



  assign tmp_36 = tmp_10 == tmp_3;



  assign tmp_15 = (tmp_36 == 1'b0 ? obj_validInHighFlag_2 :
              obj_validInHighFlag_1);



  assign tmp_37 = ( ! tmp_15) && ( ! tmp_22);



  assign tmp_13 = (tmp_37 == 1'b0 ? out_8 :
              out_9);



  assign tmp_38 = (tmp_13 == 1'b0 ? tmp_8 :
              obj_readyOut_3);



  always @(posedge clk or posedge reset)
    begin : obj_delayedReady_reg_process
      if (reset == 1'b1) begin
        obj_delayedReady <= 1'b1;
      end
      else begin
        if (enb_1_32_0) begin
          obj_delayedReady <= tmp_38;
        end
      end
    end



  assign tmp_39 = obj_delayedReady && valid;



  assign tmp_33 = (tmp_39 == 1'b0 ? out_10 :
              out_11);



  whdlOFDMTx_symbolFormation u_symbolFormation (.clk(clk),
                                                .reset(reset),
                                                .enb_1_32_0(enb_1_32_0),
                                                .tmp_re(data_re),  // sfix16_En14
                                                .tmp_im(data_im),  // sfix16_En14
                                                .tmp(tmp_33),
                                                .varargout_1_re(varargout_1_re),  // sfix16_En14
                                                .varargout_1_im(varargout_1_im),  // sfix16_En14
                                                .varargout_2(varargout_2)
                                                );

  whdlOFDMTx_dsphdl_IFFT u_dsphdl_IFFT (.clk(clk),
                                        .reset(reset),
                                        .enb_1_32_0(enb_1_32_0),
                                        .dataIn_re(varargout_1_re),  // sfix16_En14
                                        .dataIn_im(varargout_1_im),  // sfix16_En14
                                        .validIn(varargout_2),
                                        .dataOut_re(varargout_1_re_1),  // sfix16_En14
                                        .dataOut_im(varargout_1_im_1),  // sfix16_En14
                                        .validOut(varargout_2_1)
                                        );

  whdlOFDMTx_HDLFFTShiftMod u_HDLFFTShiftMod (.clk(clk),
                                              .reset(reset),
                                              .enb_1_32_0(enb_1_32_0),
                                              .varargout_1_re(varargout_1_re_1),  // sfix16_En14
                                              .varargout_1_im(varargout_1_im_1),  // sfix16_En14
                                              .varargout_2(varargout_2_1),
                                              .varargout_1_re_1(varargout_1_re_2),  // sfix16_En14
                                              .varargout_1_im_1(varargout_1_im_2),  // sfix16_En14
                                              .varargout_2_1(varargout_2_2)
                                              );

  whdlOFDMTx_CPAddition u_CPAddition (.clk(clk),
                                      .reset(reset),
                                      .enb_1_32_0(enb_1_32_0),
                                      .varargout_1_re(varargout_1_re_2),  // sfix16_En14
                                      .varargout_1_im(varargout_1_im_2),  // sfix16_En14
                                      .varargout_2(varargout_2_2),
                                      .varargout_1_re_1(varargout_1_re_3),  // sfix16_En14
                                      .varargout_1_im_1(varargout_1_im_3),  // sfix16_En14
                                      .varargout_2_1(varargout_2_3)
                                      );

  always @(posedge clk or posedge reset)
    begin : obj_dataOut_reg_process
      if (reset == 1'b1) begin
        data_re_1 <= 16'sb0000000000000000;
        data_im_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          data_re_1 <= varargout_1_re_3;
          data_im_1 <= varargout_1_im_3;
        end
      end
    end



  assign data1_re = data_re_1;

  assign data1_im = data_im_1;

  always @(posedge clk or posedge reset)
    begin : obj_validOut_reg_process
      if (reset == 1'b1) begin
        valid_1 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          valid_1 <= varargout_2_3;
        end
      end
    end



  assign valid1 = valid_1;

  assign tmp_40 = tmp_3 == 13'b0000000000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp146
  assign tmp_41 = tmp_3 - 13'b0000000000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp146
  assign obj_readyLast = 13'b0000000000001;



  assign tmp_42 = (tmp_40 == 1'b0 ? tmp_41 :
              obj_readyLast);



  assign tmp_43 = tmp_10 == tmp_42;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp174
  assign obj_readyFlag = 1'b0;



  assign tmp_44 = tmp_4 != 13'b0000000000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp139
  assign obj_readyFlag_1 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp139
  assign obj_readyFlag_2 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp117
  assign tmp_45 = (tmp_44 == 1'b0 ? obj_readyFlag_1 :
              obj_readyFlag_2);



  assign tmp_46 = obj_readyFlag_3 && valid;



  assign tmp_47 = (tmp_46 == 1'b0 ? obj_readyFlag_3 :
              obj_readyFlag);



  assign tmp_48 = (tmp_43 == 1'b0 ? tmp_47 :
              tmp_45);



  always @(posedge clk or posedge reset)
    begin : obj_readyFlag_reg_process
      if (reset == 1'b1) begin
        obj_readyFlag_3 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_readyFlag_3 <= tmp_48;
        end
      end
    end



  assign tmp_49 = obj_readyFlag_3 && valid;



  assign p115tmp_1 = {1'b0, tmp_18};
  assign p115tmp_2 = {1'b0, tmp_4};
  assign tmp_50 = p115tmp_1 == (p115tmp_2 - 14'b00000000000001);



  assign tmp_51 = obj_readyFlag_3 && valid;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp183
  assign obj_triggerReady = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp113
  assign obj_triggerReady_1 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp171
  assign tmp_52 = (obj_triggerReady_2 == 1'b0 ? obj_triggerReady_2 :
              obj_triggerReady);



  assign tmp_53 = (tmp_51 == 1'b0 ? tmp_52 :
              obj_triggerReady_2);



  assign tmp_54 = (tmp_50 == 1'b0 ? tmp_53 :
              obj_triggerReady_1);



  // HDL code generation from MATLAB function: SystemCore_stepImpl
  always @(posedge clk or posedge reset)
    begin : obj_triggerReady_reg_process
      if (reset == 1'b1) begin
        obj_triggerReady_2 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_triggerReady_2 <= tmp_54;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp186
  always @(posedge clk or posedge reset)
    begin : obj_readyOut_reg_process
      if (reset == 1'b1) begin
        obj_readyOut_4 <= 1'b1;
      end
      else begin
        if (enb_1_32_0) begin
          obj_readyOut_4 <= tmp_38;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp186
  assign varargout_3 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp177
  assign tmp_55 = (obj_triggerReady_2 == 1'b0 ? obj_readyOut_4 :
              varargout_3);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp177
  assign varargout_3_1 = 1'b0;



  assign ready = (tmp_49 == 1'b0 ? tmp_55 :
              varargout_3_1);



endmodule  // whdlOFDMTx_OFDM_Modulator

