// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_MATLAB_Function1_block.v
// Created: 2023-05-02 12:36:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_MATLAB_Function1_block
// Source Path: whdlOFDMTx/Frame Generator/Data/Data Chain/Symbol Interleaver/Interleaver/Generate Ready/MATLAB Function1
// Hierarchy Level: 8
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_MATLAB_Function1_block
          (clk,
           reset,
           enb,
           trigger,
           out);


  input   clk;
  input   reset;
  input   enb;
  input   trigger;
  output  out;


  reg  out_1;
  reg [2:0] count;  // ufix3
  reg  state;
  reg [2:0] count_next;  // ufix3
  reg  state_next;
  reg [2:0] count_temp;  // ufix3
  reg  state_temp;


  always @(posedge clk or posedge reset)
    begin : MATLAB_Function1_process
      if (reset == 1'b1) begin
        count <= 3'b000;
        state <= 1'b0;
      end
      else begin
        if (enb) begin
          count <= count_next;
          state <= state_next;
        end
      end
    end

  always @(count, state, trigger) begin
    count_temp = count;
    state_temp = state;
    // %% Executes in current clock cycle
    if (trigger) begin
      state_temp = 1'b1;
      count_temp = 3'b000;
    end
    if (state_temp && ( ! trigger)) begin
      count_temp = count_temp + 3'b001;
    end
    if (count_temp == 3'b100) begin
      state_temp = 1'b0;
    end
    out_1 = state_temp;
    count_next = count_temp;
    state_next = state_temp;
  end



  assign out = out_1;

endmodule  // whdlOFDMTx_MATLAB_Function1_block

