// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_Generate_Current_Frame_Status.v
// Created: 2023-05-02 12:36:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_Generate_Current_Frame_Status
// Source Path: whdlOFDMTx/Frame Generator/Data/Data Chain/Symbol Interleaver/Interleaver/Write Logic/Handle Input 
// Control Signals/Generate Current Frame Statu
// Hierarchy Level: 9
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_Generate_Current_Frame_Status
          (clk,
           reset,
           enb,
           start,
           end_rsvd,
           frameOn);


  input   clk;
  input   reset;
  input   enb;
  input   start;
  input   end_rsvd;
  output  frameOn;


  reg  Delay3_out1;
  wire Logical_Operator7_out1;
  wire Logical_Operator6_out1;
  wire Logical_Operator4_out1;
  wire Constant3_out1;
  wire Constant2_out1;
  wire Switch2_out1;
  reg  Unit_Delay_Enabled_Synchronous1_out1;


  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= start;
        end
      end
    end



  assign Logical_Operator7_out1 =  ~ Delay3_out1;



  assign Logical_Operator6_out1 = Logical_Operator7_out1 & end_rsvd;



  assign Logical_Operator4_out1 = start | Logical_Operator6_out1;



  assign Constant3_out1 = 1'b0;



  assign Constant2_out1 = 1'b1;



  assign Switch2_out1 = (start == 1'b0 ? Constant3_out1 :
              Constant2_out1);



  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Synchronous1_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous1_out1 <= 1'b0;
      end
      else begin
        if (enb && Logical_Operator4_out1) begin
          Unit_Delay_Enabled_Synchronous1_out1 <= Switch2_out1;
        end
      end
    end



  assign frameOn = Unit_Delay_Enabled_Synchronous1_out1;

endmodule  // whdlOFDMTx_Generate_Current_Frame_Status

