// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_Discrete_FIR_Filter.v
// Created: 2023-05-02 12:36:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_Discrete_FIR_Filter
// Source Path: whdlOFDMTx/Discrete FIR Filter
// Hierarchy Level: 2
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_Discrete_FIR_Filter
          (clk,
           reset,
           enb_1_32_0,
           dataIn_re,
           dataIn_im,
           validIn,
           dataOut_re,
           dataOut_im,
           clock_Fir_out,
           validOut);


  input   clk;
  input   reset;
  input   enb_1_32_0;
  input   signed [15:0] dataIn_re;  // sfix16_En14
  input   signed [15:0] dataIn_im;  // sfix16_En14
  input   validIn;
  output  signed [15:0] dataOut_re;  // sfix16_En13
  output  signed [15:0] dataOut_im;  // sfix16_En13
  output  validOut;
  output  clock_Fir_out;


  wire syncReset;


  assign syncReset = 1'b0;
  
  assign clock_Fir_out = validOut;



  whdlOFDMTx_Filter u_FilterBank (.clk(clk),
                                  .reset(reset),
                                  .enb_1_32_0(enb_1_32_0),
                                  .dataIn_re(dataIn_re),  // sfix16_En14
                                  .dataIn_im(dataIn_im),  // sfix16_En14
                                  .validIn(validIn),
                                  .syncReset(syncReset),
                                  .dataOut_re(dataOut_re),  // sfix16_En13
                                  .dataOut_im(dataOut_im),  // sfix16_En13
                                  .validOut(validOut)
                                  );

endmodule  // whdlOFDMTx_Discrete_FIR_Filter

