// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_Multiplex_Preamble_Signals.v
// Created: 2023-05-02 12:36:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_Multiplex_Preamble_Signals
// Source Path: whdlOFDMTx/Multiplexer/Multiplex Preamble Signals
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_Multiplex_Preamble_Signals
          (ss_re,
           ss_im,
           ssValid,
           rs,
           rsValid,
           pilot,
           pilotValid,
           preambleOut_re,
           preambleOut_im,
           preambleValid);


  input   signed [15:0] ss_re;  // sfix16_En14
  input   signed [15:0] ss_im;  // sfix16_En14
  input   ssValid;
  input   signed [15:0] rs;  // sfix16_En14
  input   rsValid;
  input   signed [15:0] pilot;  // sfix16_En14
  input   pilotValid;
  output  signed [15:0] preambleOut_re;  // sfix16_En14
  output  signed [15:0] preambleOut_im;  // sfix16_En14
  output  preambleValid;


  wire [2:0] selLine;  // ufix3
  wire signed [15:0] Real_Imag_to_Complex_out1_re;  // sfix16_En14
  wire signed [15:0] Real_Imag_to_Complex_out1_im;  // sfix16_En14
  wire signed [15:0] Real_Imag_to_Complex1_out1_re;  // sfix16_En14
  wire signed [15:0] Real_Imag_to_Complex1_out1_im;  // sfix16_En14
  wire signed [15:0] Multiport_Switch_out1_re;  // sfix16_En14
  wire signed [15:0] Multiport_Switch_out1_im;  // sfix16_En14
  wire Logical_Operator_out1;


  whdlOFDMTx_Priority_Encoder u_Priority_Encoder (.ssValid(ssValid),
                                                  .rsValid(rsValid),
                                                  .pilotValid(pilotValid),
                                                  .selLine(selLine)  // ufix3
                                                  );

  assign Real_Imag_to_Complex_out1_re = rs;
  assign Real_Imag_to_Complex_out1_im = 16'sb0000000000000000;



  assign Real_Imag_to_Complex1_out1_re = pilot;
  assign Real_Imag_to_Complex1_out1_im = 16'sb0000000000000000;



  assign Multiport_Switch_out1_re = (selLine == 3'b000 ? ss_re :
              (selLine == 3'b001 ? Real_Imag_to_Complex_out1_re :
              Real_Imag_to_Complex1_out1_re));
  assign Multiport_Switch_out1_im = (selLine == 3'b000 ? ss_im :
              (selLine == 3'b001 ? Real_Imag_to_Complex_out1_im :
              Real_Imag_to_Complex1_out1_im));



  assign preambleOut_re = Multiport_Switch_out1_re;

  assign preambleOut_im = Multiport_Switch_out1_im;

  assign Logical_Operator_out1 = ssValid | (pilotValid | rsValid);



  assign preambleValid = Logical_Operator_out1;

endmodule  // whdlOFDMTx_Multiplex_Preamble_Signals

