// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_Filter.v
// Created: 2023-05-02 12:36:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_Filter
// Source Path: whdlOFDMTx/Discrete FIR Filter/Filter
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_Filter
          (clk,
           reset,
           enb_1_32_0,
           dataIn_re,
           dataIn_im,
           validIn,
           syncReset,
           dataOut_re,
           dataOut_im,
           validOut);


  input   clk;
  input   reset;
  input   enb_1_32_0;
  input   signed [15:0] dataIn_re;  // sfix16_En14
  input   signed [15:0] dataIn_im;  // sfix16_En14
  input   validIn;
  input   syncReset;
  output  signed [15:0] dataOut_re;  // sfix16_En13
  output  signed [15:0] dataOut_im;  // sfix16_En13
  output  validOut;


  reg  dinRegVld;
  reg signed [15:0] dinReg_0_re;  // sfix16_En14
  reg signed [15:0] dinReg2_0_re;  // sfix16_En14
  wire signed [15:0] CoefOut_0;  // sfix16_En15
  wire signed [15:0] CoefOut_1;  // sfix16_En15
  wire signed [15:0] CoefOut_2;  // sfix16_En15
  wire signed [15:0] CoefOut_3;  // sfix16_En15
  wire signed [15:0] CoefOut_4;  // sfix16_En15
  wire signed [15:0] CoefOut_5;  // sfix16_En15
  wire signed [15:0] CoefOut_6;  // sfix16_En15
  wire signed [15:0] CoefOut_7;  // sfix16_En15
  wire signed [15:0] CoefOut_8;  // sfix16_En15
  wire signed [15:0] CoefOut_9;  // sfix16_En15
  wire signed [15:0] CoefOut_10;  // sfix16_En15
  reg  dinReg2Vld;
  wire signed [15:0] dout_1_re;  // sfix16_En13
  wire doutVld;
  reg signed [15:0] dinReg_0_im;  // sfix16_En14
  reg signed [15:0] dinReg2_0_im;  // sfix16_En14
  wire signed [15:0] dout_1_im;  // sfix16_En13
  wire doutVlddeadOutdeadOut;


  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dinReg_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn_re;
            end
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dinReg2_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_0_re;
            end
          end
        end
      end
    end



  whdlOFDMTx_FilterCoef u_CoefTable_1 (.CoefOut_0(CoefOut_0),  // sfix16_En15
                                       .CoefOut_1(CoefOut_1),  // sfix16_En15
                                       .CoefOut_2(CoefOut_2),  // sfix16_En15
                                       .CoefOut_3(CoefOut_3),  // sfix16_En15
                                       .CoefOut_4(CoefOut_4),  // sfix16_En15
                                       .CoefOut_5(CoefOut_5),  // sfix16_En15
                                       .CoefOut_6(CoefOut_6),  // sfix16_En15
                                       .CoefOut_7(CoefOut_7),  // sfix16_En15
                                       .CoefOut_8(CoefOut_8),  // sfix16_En15
                                       .CoefOut_9(CoefOut_9),  // sfix16_En15
                                       .CoefOut_10(CoefOut_10)  // sfix16_En15
                                       );

  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end



  whdlOFDMTx_subFilter u_subFilter_1_re (.clk(clk),
                                         .reset(reset),
                                         .enb_1_32_0(enb_1_32_0),
                                         .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                         .coefIn_0(CoefOut_0),  // sfix16_En15
                                         .coefIn_1(CoefOut_1),  // sfix16_En15
                                         .coefIn_2(CoefOut_2),  // sfix16_En15
                                         .coefIn_3(CoefOut_3),  // sfix16_En15
                                         .coefIn_4(CoefOut_4),  // sfix16_En15
                                         .coefIn_5(CoefOut_5),  // sfix16_En15
                                         .coefIn_6(CoefOut_6),  // sfix16_En15
                                         .coefIn_7(CoefOut_7),  // sfix16_En15
                                         .coefIn_8(CoefOut_8),  // sfix16_En15
                                         .coefIn_9(CoefOut_9),  // sfix16_En15
                                         .coefIn_10(CoefOut_10),  // sfix16_En15
                                         .dinRegVld(dinReg2Vld),
                                         .syncReset(syncReset),
                                         .dout_1_re(dout_1_re),  // sfix16_En13
                                         .doutVld(doutVld)
                                         );

  assign dataOut_re = dout_1_re;

  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        dinReg_0_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dinReg_0_im <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_im <= dataIn_im;
            end
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        dinReg2_0_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_im <= 16'sb0000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_im <= dinReg_0_im;
            end
          end
        end
      end
    end



  whdlOFDMTx_subFilter u_subFilter_1_im (.clk(clk),
                                         .reset(reset),
                                         .enb_1_32_0(enb_1_32_0),
                                         .dinReg2_0_re(dinReg2_0_im),  // sfix16_En14
                                         .coefIn_0(CoefOut_0),  // sfix16_En15
                                         .coefIn_1(CoefOut_1),  // sfix16_En15
                                         .coefIn_2(CoefOut_2),  // sfix16_En15
                                         .coefIn_3(CoefOut_3),  // sfix16_En15
                                         .coefIn_4(CoefOut_4),  // sfix16_En15
                                         .coefIn_5(CoefOut_5),  // sfix16_En15
                                         .coefIn_6(CoefOut_6),  // sfix16_En15
                                         .coefIn_7(CoefOut_7),  // sfix16_En15
                                         .coefIn_8(CoefOut_8),  // sfix16_En15
                                         .coefIn_9(CoefOut_9),  // sfix16_En15
                                         .coefIn_10(CoefOut_10),  // sfix16_En15
                                         .dinRegVld(dinReg2Vld),
                                         .syncReset(syncReset),
                                         .dout_1_re(dout_1_im),  // sfix16_En13
                                         .doutVld(doutVlddeadOutdeadOut)
                                         );

  assign dataOut_im = dout_1_im;

  assign validOut = doutVld;

endmodule  // whdlOFDMTx_Filter

